n, m = map(int, input().split())
a = list(map(int, input().split()))
b = list(map(int, input().split()))
A = set(a)
B = set(b)
giao = sorted(A & B)
hieu_A_B = sorted(A - B)
hieu_B_A = sorted(B - A)
print(*giao)
print(*hieu_A_B)
print(*hieu_B_A)
